allowBuilds:
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.8
  vitest: 4.1.10
  vite-plus: ^0.2.8
overrides:
  vite: "catalog:"
  vitest: "catalog:"
patchedDependencies:
  '@storybook/addon-svelte-csf@5.1.2': patches/@storybook__addon-svelte-csf@5.1.2.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
